site_name: FluentDo Agent Documentation
nav:
  - Home: index.md
  - Features:
    - Record Deduplication: features/record-deduplication.md
  - Security:
    - Overview: security.md
    - CVE Information: security/cves.md
  - Supported Platforms: supported-platforms.md
  - Version Mapping: version-mapping.md
plugins:
  - privacy

theme:
  name: material
  highlightjs: true
  copyright: FluentDo 2025
  custom_dir: overrides

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: yellow
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: yellow
      accent: deep orange
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
extra:
  homepage: https://fluent.do
  # Disable made by mkdocs
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: Github
        checked: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FluentDo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fluent-do
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@fluent.do
copyright: >
  Copyright &copy; 2025 FluentDo
  <a href="#__consent">Change cookie settings</a>
