site_name: Telemetry Forge Agent Documentation
site_url: https://telemetryforge.io
nav:
  - Home: index.md
  - Features:
    - Overview: features/index.md
    - Record Deduplication: features/record-deduplication.md
    - Log Sampling: features/log-sampling.md
    - Git Configuration Auto-Reload: features/git-config-auto-reload.md
    - Hardening and Optimisation: build-optimisations.md
  - Security:
    - Overview: security.md
    - CVE Information: security/cves.md
    - Current Triaged Vulnerabilities: security/triaged.md
  - Supported Platforms: supported-platforms.md
  - Version Mapping: version-mapping.md
plugins:
  - privacy
  - offline
  - search
  - social
  - meta
markdown_extensions:
  - pymdownx.snippets

theme:
  name: material
  highlightjs: true
  copyright: Telemetry Forge 2026
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: yellow
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: yellow
      accent: deep orange
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
extra:
  homepage: https://telemetryforge.io
  # Disable made by mkdocs
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: Github
        checked: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telemetryforge
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/telemetry-forge
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@telemetryforge.io
copyright: >
  Copyright &copy; 2025 - 2026 Telemetry Forge
  <a href="#__consent">Change cookie settings</a>
