name: Reusable workflow to invoke add-mapping-version.sh
on:
  workflow_call:
    inputs:
      agent-version:
        description: 'The version of the FluentDo agent to add'
        required: true
        type: string
      oss-version:
        description: 'The version of the underlying OSS Fluent Bit that the agent is based on'
        required: true
        type: string
      dry-run:
        description: 'Whether to run in dry-run mode'
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        description: 'GitHub token for authentication'
jobs:
  add-mapping-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            repository: fluentdo/documentation
            token: ${{ secrets.github-token }}

      - name: Add mapping version
        run: |
          chmod +x scripts/add-mapping-version.sh
          scripts/add-mapping-version.sh
        shell: bash
        env:
          NEW_AGENT_VERSION: ${{ inputs.agent-version }}
          NEW_OSS_VERSION: ${{ inputs.oss-version }}
          DRY_RUN: ${{ inputs.dry-run }}

      - name: Create a PR with the update
        if: ${{ !inputs.dry-run }}
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "ci: add mapping version for agent ${{ inputs.agent-version }}"
          signoff: true
          base: main
          branch: ci_update-version-${{ inputs.agent-version }}
          delete-branch: true
          title: "ci: add mapping version for agent ${{ inputs.agent-version }}"
          token: ${{ secrets.github-token }}
          labels: ci,automerge
          body: |
            Mapping version added for FluentDo agent ${{ inputs.agent-version }}:
            - Agent Version: `${{ inputs.agent-version }}`
            - OSS Version: `${{ inputs.oss-version }}`

            This PR was created to update the version mapping in the documentation.

            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        shell: bash

    #   - name: Enable Pull Request Automerge
    #     if: ${{ steps.cpr.outputs.pull-request-number }}
    #     run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
    #     env:
    #       GH_TOKEN: ${{ secrets.github-token }}