name: Reusable workflow to invoke add-mapping-version.sh
on:
  workflow_call:
    inputs:
      agent-version:
        description: 'The version of the FluentDo agent to add'
        required: true
        type: string
      oss-version:
        description: 'The version of the underlying OSS Fluent Bit that the agent is based on'
        required: true
        type: string
      dry-run:
        description: 'Whether to run in dry-run mode'
        required: false
        type: boolean
        default: false
jobs:
  add-mapping-version:
    name: Add Mapping Version ${{ inputs.agent-version }} --> ${{ inputs.oss-version }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/841522437311/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "terraform-infra@infrastructure-464010.iam.gserviceaccount.com"

      - id: get-secrets
        name: Get secrets from GCP Secret Manager
        # This step retrieves secrets from GCP Secret Manager and sets them as outputs
        # The secrets can then be accessed in subsequent steps using ${{ steps.get-secrets.outputs.<secret_name> }}
        uses: "google-github-actions/get-secretmanager-secrets@v3"
        with:
          secrets: |-
            github-pat:projects/626836145334/secrets/GITHUB_CI_PAT

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
            repository: fluentdo/documentation
            token: ${{ steps.get-secrets.outputs.github-pat }}

      - name: Install tools
        run: |
          curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin
          curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin
        shell: bash

      - name: Ensure we authenticate the GH CLI
        run: |
          gh auth status || echo "Not authenticated"
        shell: bash
        env:
          GH_TOKEN: ${{ steps.get-secrets.outputs.github-pat }}

      - name: Add mapping version
        run: |
          chmod +x scripts/add-mapping-version.sh
          scripts/add-mapping-version.sh
        shell: bash
        env:
          NEW_AGENT_VERSION: ${{ inputs.agent-version }}
          NEW_OSS_VERSION: ${{ inputs.oss-version }}
          DRY_RUN: ${{ inputs.dry-run }}
          GH_TOKEN: ${{ steps.get-secrets.outputs.github-pat }}

      - name: Debug info
        run: |
          git status
          git diff
        shell: bash

      - name: Create a PR with the update
        if: ${{ !inputs.dry-run }}
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "ci: add mapping version for agent ${{ inputs.agent-version }}"
          signoff: true
          base: main
          branch: ci_update-version-${{ inputs.agent-version }}
          delete-branch: true
          title: "ci: add mapping version for agent ${{ inputs.agent-version }}"
          token: ${{ steps.get-secrets.outputs.github-pat }}
          labels: ci,automerge
          body: |
            Mapping version added for FluentDo agent ${{ inputs.agent-version }}:
            - Agent Version: `${{ inputs.agent-version }}`
            - OSS Version: `${{ inputs.oss-version }}`

            This PR was created to update the version mapping in the documentation.

            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        shell: bash

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.get-secrets.outputs.github-pat }}
